### ISSUE TITLE
Awesome header and footer

### ISSUE THREAD

**Issue by paleomedia** [ambientsensors-bootcamp/idleg#13]
Add some rad Angular Material Design header and footer stuff:
For ideas: http://www.idleg.info/
http://blog.sodhanalibrary.com/2015/07/header-design-with-angularjs-material-ui.html#.WZEF-VWGPb0
http://www.bossable.com/1338/angular-material-design-toolbar-examples/

**Comment by MoteebN** [comment]
These are some good examples, thanks for links I'll see what I can do!
